name: Deploy Overlay to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Reste en v4 car elle est compatible

      - name: Setup Pages
        uses: actions/configure-pages@v5 # Mis à jour en v5 pour Node 24+

      - name: Upload artifact
        uses: actions/upload-artifact@v4 # Reste en v4 car elle est compatible

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # Reste en v4 car elle est compatible
